import { Raleway } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import { NavbarSection } from '@/components'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'GM Consciencia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={raleway.className} style={{ backgroundColor: "#f8f6f5" }}>
        <Providers>
          <NavbarSection />
          {children}
        </Providers>
      </body>
    </html>
  )
}
